### ISSUE TITLE
Qiqqa Explorer: clicking Refresh seems to (re)trigger OCR activity for many files in the library

### ISSUE THREAD

**Issue by GerHobbelt** [GerHobbelt/qiqqa-open-source#1]
Happens with test Qiqqa IntraNet library `debwot`. 

CPU goes to 100% and after a while the statusbar at bottom mentions several 1000's pages need to be OCR'ed. 🤔

**Comment by GerHobbelt** [comment]
Example/Analysis:

Qiqqa collects the text in the PDF and therefore scans the OCR text files.
In this particular case it's page #135 which is not found in page-group file 

D:\Qiqqa\base\ocr\\BD\BD3C3A5B3E4FF2C6FE4D5D9F1EE89E9B6A9520E5.textgroup.121_to_140.txt

and consequently a single-page OCR job is triggered.

**Comment by GerHobbelt** [comment]
## Example Analysis (continued)

And then it turns out QiqqaOCR.exe b0rks fatally inside Tesseract -- or rather: it crashes in the bitmap LockPixel API:

note two things in the log below: QiqqaOCR calculates some crazy rectangle(s) with NEGATIVE HEIGHT and when that is fed to Tesseract+Bitmap, things go South at high velocity. 

This is a bug that has apparently been a long time present in Qiqqa/QiqqaOCR.

The Logging is from an augmented QiqqaOCR codebase to help observe what happ'nin':

```
20191003.215839 [OCR] INFO  [ThreadOCR] [3.101M] +Doing OCR
20191003.215839 [OCR] INFO  [ThreadOCR] [3.109M] Getting regions
20191003.215840 [OCR] INFO  [ThreadOCR] [3.119M] Got 13 regions
20191003.215840 [OCR] WARN  [ThreadOCR] [3.119M] Calculated region height is negative or zero: 0 <-- CURRENT:0:TOP - LAST:0:TOP
20191003.215840 [OCR] WARN  [ThreadOCR] [3.119M] Calculated region {X=0,Y=0,Width=0,Height=0} <-- CURRENT:0:TOP - LAST:0:TOP
20191003.215840 [OCR] WARN  [ThreadOCR] [3.127M] Calculated region height is negative or zero: 0 <-- CURRENT:0:BLANKS - LAST:0:TOP
20191003.215840 [OCR] WARN  [ThreadOCR] [3.127M] Calculated region {X=0,Y=0,Width=0,Height=0} <-- CURRENT:0:BLANKS - LAST:0:TOP
20191003.215840 [OCR] WARN  [ThreadOCR] [3.127M] Calculated region {X=827,Y=0,Width=827,Height=124} <-- CURRENT:124:PIXELS - LAST:0:BLANKS
20191003.215840 [OCR] WARN  [ThreadOCR] [3.127M] Calculated region {X=0,Y=124,Width=1654,Height=103} <-- CURRENT:227:BLANKS - LAST:124:PIXELS
20191003.215840 [OCR] WARN  [ThreadOCR] [3.135M] Calculated region {X=827,Y=227,Width=827,Height=50} <-- CURRENT:277:PIXELS - LAST:227:BLANKS
20191003.215840 [OCR] WARN  [ThreadOCR] [3.135M] Calculated region {X=0,Y=277,Width=1654,Height=785} <-- CURRENT:1062:BLANKS - LAST:277:PIXELS
20191003.215840 [OCR] WARN  [ThreadOCR] [3.135M] Calculated region height is negative or zero: -785 <-- CURRENT:277:PIXELS - LAST:1062:BLANKS
20191003.215840 [OCR] WARN  [ThreadOCR] [3.135M] Calculated region {X=827,Y=1062,Width=827,Height=-785} <-- CURRENT:277:PIXELS - LAST:1062:BLANKS
20191003.215840 [OCR] WARN  [ThreadOCR] [3.135M] Calculated region {X=0,Y=277,Width=1654,Height=785} <-- CURRENT:1062:BLANKS - LAST:277:PIXELS
20191003.215840 [OCR] WARN  [ThreadOCR] [3.143M] Calculated region height is negative or zero: -785 <-- CURRENT:277:PIXELS - LAST:1062:BLANKS
20191003.215840 [OCR] WARN  [ThreadOCR] [3.143M] Calculated region {X=827,Y=1062,Width=827,Height=-785} <-- CURRENT:277:PIXELS - LAST:1062:BLANKS
20191003.215840 [OCR] WARN  [ThreadOCR] [3.143M] Calculated region {X=0,Y=277,Width=1654,Height=964} <-- CURRENT:1241:BLANKS - LAST:277:PIXELS
20191003.215840 [OCR] WARN  [ThreadOCR] [3.143M] Calculated region height is negative or zero: -174 <-- CURRENT:1067:PIXELS - LAST:1241:BLANKS
20191003.215840 [OCR] WARN  [ThreadOCR] [3.151M] Calculated region {X=827,Y=1241,Width=827,Height=-174} <-- CURRENT:1067:PIXELS - LAST:1241:BLANKS
20191003.215840 [OCR] WARN  [ThreadOCR] [3.151M] Calculated region {X=0,Y=1067,Width=1654,Height=174} <-- CURRENT:1241:BLANKS - LAST:1067:PIXELS
20191003.215840 [OCR] WARN  [ThreadOCR] [3.151M] Calculated region {X=827,Y=1241,Width=827,Height=1098} <-- CURRENT:2339:BOTTOM - LAST:1241:BLANKS
20191003.215840 [OCR] DEBUG [ThreadOCR] [3.151M] Dumping page 6 PNG image to file D:\Qiqqa\base\C9F0D079-EE4C-4A15-8547-72164A7A356D\documents\9\9EEFF1545A5CDA5850D698A202563CDC6322CE0.pdf.6-ocr.png
20191003.215840 [OCR] INFO  [ThreadOCR] [3.173M] Doing OCR for region {X=0,Y=0,Width=827,Height=124} on bitmap WxH: 1654x2339
20191003.215840 [OCR] INFO  [ThreadOCR] [3.173M] Got 1 words
20191003.215840 [OCR] INFO  [ThreadOCR] [3.173M] Doing OCR for region {X=827,Y=0,Width=827,Height=124} on bitmap WxH: 1654x2339
20191003.215840 [OCR] INFO  [ThreadOCR] [3.181M] Got 1 words
20191003.215840 [OCR] INFO  [ThreadOCR] [3.181M] Doing OCR for region {X=0,Y=124,Width=1654,Height=103} on bitmap WxH: 1654x2339
20191003.215840 [OCR] INFO  [ThreadOCR] [3.181M] Got 1 words
20191003.215840 [OCR] INFO  [ThreadOCR] [3.181M] Doing OCR for region {X=0,Y=227,Width=827,Height=50} on bitmap WxH: 1654x2339
20191003.215840 [OCR] INFO  [ThreadOCR] [3.181M] Got 1 words
20191003.215840 [OCR] INFO  [ThreadOCR] [3.181M] Doing OCR for region {X=827,Y=227,Width=827,Height=50} on bitmap WxH: 1654x2339
20191003.215840 [OCR] INFO  [ThreadOCR] [3.189M] Got 1 words
20191003.215840 [OCR] INFO  [ThreadOCR] [3.189M] Doing OCR for region {X=0,Y=277,Width=1654,Height=785} on bitmap WxH: 1654x2339
20191003.215851 [OCR] INFO  [ThreadOCR] [3.451M] Got 413 words
20191003.215851 [OCR] INFO  [ThreadOCR] [3.484M] Doing OCR for region {X=0,Y=1062,Width=827,Height=-785} on bitmap WxH: 1654x2339
20191003.215851 [OCR] ERROR [ThreadOCR] [3.517M] Problem while doing OCR for file D:\Qiqqa\base\C9F0D079-EE4C-4A15-8547-72164A7A356D\documents\9\9EEFF1545A5CDA5850D698A202563CDC6322CE0.pdf @ page 6

System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap.LockBits(Rectangle rect, ImageLockMode flags, PixelFormat format, BitmapData bitmapData)
   at System.Drawing.Bitmap.LockBits(Rectangle rect, ImageLockMode flags, PixelFormat format)
   at tessnet2.Tesseract.PutImage(Bitmap bitmap, Rectangle rect) in z:\dev\interne\cs\tesseract-ocr-svn\dotnet\tessnet2.cpp:line 327
   at tessnet2.Tesseract.DoOCR(Bitmap bitmap, Rectangle rect) in z:\dev\interne\cs\tesseract-ocr-svn\dotnet\tessnet2.cpp:line 388
   at QiqqaOCR.OCREngine.DoOCR(String pdf_filename, Int32 page_number) in W:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\qiqqa\QiqqaOCR\OCREngine.cs:line 279
   at QiqqaOCR.OCREngine.ThreadOCRMainEntry(Object arg) in W:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\qiqqa\QiqqaOCR\OCREngine.cs:line 168
20191003.215851 [OCR] INFO  [Main] [3.525M] Both text extract and OCR have had an exception, so exiting
20191003.215851 [OCR] INFO  [Main] [3.533M] +Writing empty OCR to file C:\Users\Ger\AppData\Local\Temp\TempFile.aec52fbb-2cde-43fd-9c47-8bd72eddc0bb.txt
```

**Comment by GerHobbelt** [comment]
Fix upcoming: No more crash and sanitized the region rectangles.

Test log output (note the warnings about negative height and MERGED rectangles: the old code would produce overlapping rectangles around those neg/zero-height rects and thus aggravate the matter.

See the attached images which has the QiqqaOCR generated rectangles drawn in (green are okay rects)

![9EEFF1545A5CDA5850D698A202563CDC6322CE0 pdf 6-ocr](https://user-images.githubusercontent.com/402462/66169309-49aed200-e640-11e9-9cc7-69f6aa57abdb.png)

```
$ ./QiqqaOCR.exe SINGLE "D:\Qiqqa\base\C9F0D079-EE4C-4A15-8547-72164A7A356D\documents\9\9EEFF1545A5CDA5850D698A202563CDC6322CE0.pdf" 6 "C:\Users\Ger\AppData\Local\Temp\\TempFile.aec52fbb-2cde-43fd-9c47-8bd72eddc0bb.txt" "" ""
20191003.224148 [OCR] INFO  [Main] [1.104M] Logging initialised.
  Stacktrace:
       at Utilities.Logging..cctor() in W:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\qiqqa\Utilities\Logging.cs:line 25
       at Utilities.Logging.Info(String msg)
       at QiqqaOCR.OCREngine.MainEntry(String[] args, Boolean no_kill) in W:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\qiqqa\QiqqaOCR\OCREngine.cs:line 62
       at QiqqaOCR.Program.Main(String[] args) in W:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\qiqqa\QiqqaOCR\Program.cs:line 50
20191003.224148 [OCR] INFO  [Main] [1.129M] Defaulting to language eng
20191003.224148 [OCR] INFO  [Main] [1.129M] Starting the OCR thread
20191003.224148 [OCR] INFO  [ThreadOCR] [1.153M] +Rendering page 6 for PDF file D:\Qiqqa\base\C9F0D079-EE4C-4A15-8547-72164A7A356D\documents\9\9EEFF1545A5CDA5850D698A202563CDC6322CE0.pdf
20191003.224148 [OCR] INFO  [ThreadOCR] [1.153M] +Initialising SoraxPDFRendererDLLWrapper
20191003.224148 [OCR] INFO  [ThreadOCR] [1.170M] -Initialising SoraxPDFRendererDLLWrapper
20191003.224148 [OCR] INFO  [ThreadOCR] [2.788M] Disposing HDOCWrapper
20191003.224148 [OCR] DEBUG [ThreadOCR] [2.788M] HDOCWrapper::Dispose(true) @1
20191003.224148 [OCR] INFO  [ThreadOCR] [2.788M] Disposing the lucene index writer
20191003.224148 [OCR] INFO  [ThreadOCR] [3.101M] -Rendering page #6
20191003.224148 [OCR] INFO  [ThreadOCR] [3.101M] Startup directory is W:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\qiqqa\QiqqaOCR\bin\Debug
20191003.224148 [OCR] INFO  [ThreadOCR] [3.101M] Language is 'eng'
20191003.224148 [OCR] INFO  [ThreadOCR] [3.109M] +Doing OCR
20191003.224148 [OCR] INFO  [ThreadOCR] [3.109M] Getting regions
20191003.224149 [OCR] INFO  [ThreadOCR] [3.119M] Got 13 regions
20191003.224149 [OCR] WARN  [ThreadOCR] [3.119M] Calculated region height is negative or zero: 0 :: Calculated region {X=0,Y=0,Width=0,Height=0} <-- CURRENT:0:TOP - LAST:0:TOP
20191003.224149 [OCR] WARN  [ThreadOCR] [3.119M] Calculated region height is negative or zero: 0 :: Calculated region {X=0,Y=0,Width=0,Height=0} <-- CURRENT:0:BLANKS - LAST:0:TOP
20191003.224149 [OCR] WARN  [ThreadOCR] [3.127M] Calculated region height is negative or zero: -785 :: Calculated region {X=827,Y=1062,Width=827,Height=0} <-- CURRENT:277:PIXELS - LAST:1062:BLANKS
20191003.224149 [OCR] WARN  [ThreadOCR] [3.127M] Overlapping subsequent rectangles will be merged :: CURRENT:{X=0,Y=277,Width=1654,Height=785} - LAST:{X=0,Y=277,Width=1654,Height=785}
20191003.224149 [OCR] WARN  [ThreadOCR] [3.127M] --> Updated 'last' rectangle:{X=0,Y=277,Width=1654,Height=785}
20191003.224149 [OCR] WARN  [ThreadOCR] [3.135M] Calculated region height is negative or zero: -785 :: Calculated region {X=827,Y=1062,Width=827,Height=0} <-- CURRENT:277:PIXELS - LAST:1062:BLANKS
20191003.224149 [OCR] WARN  [ThreadOCR] [3.135M] Overlapping subsequent rectangles will be merged :: CURRENT:{X=0,Y=277,Width=1654,Height=964} - LAST:{X=0,Y=277,Width=1654,Height=785}
20191003.224149 [OCR] WARN  [ThreadOCR] [3.135M] --> Updated 'last' rectangle:{X=0,Y=277,Width=1654,Height=964}
20191003.224149 [OCR] WARN  [ThreadOCR] [3.135M] Calculated region height is negative or zero: -174 :: Calculated region {X=827,Y=1241,Width=827,Height=0} <-- CURRENT:1067:PIXELS - LAST:1241:BLANKS
20191003.224149 [OCR] DEBUG [ThreadOCR] [3.143M] Dumping page 6 PNG image to file D:\Qiqqa\base\C9F0D079-EE4C-4A15-8547-72164A7A356D\documents\9\9EEFF1545A5CDA5850D698A202563CDC6322CE0.pdf.6-ocr.png
20191003.224149 [OCR] INFO  [ThreadOCR] [3.156M] Doing OCR for region {X=827,Y=0,Width=827,Height=124} on bitmap WxH: 1654x2339
20191003.224149 [OCR] INFO  [ThreadOCR] [3.156M] Got 1 words
20191003.224149 [OCR] INFO  [ThreadOCR] [3.164M] Doing OCR for region {X=0,Y=124,Width=1654,Height=103} on bitmap WxH: 1654x2339
20191003.224149 [OCR] INFO  [ThreadOCR] [3.164M] Got 1 words
20191003.224149 [OCR] INFO  [ThreadOCR] [3.164M] Doing OCR for region {X=827,Y=227,Width=827,Height=50} on bitmap WxH: 1654x2339
20191003.224149 [OCR] INFO  [ThreadOCR] [3.164M] Got 1 words
20191003.224149 [OCR] INFO  [ThreadOCR] [3.164M] Doing OCR for region {X=0,Y=277,Width=1654,Height=785} on bitmap WxH: 1654x2339
20191003.224200 [OCR] INFO  [ThreadOCR] [3.427M] Got 413 words
20191003.224200 [OCR] INFO  [ThreadOCR] [3.459M] Doing OCR for region {X=0,Y=1067,Width=1654,Height=174} on bitmap WxH: 1654x2339
20191003.224203 [OCR] INFO  [ThreadOCR] [3.517M] Got 77 words
20191003.224203 [OCR] INFO  [ThreadOCR] [3.525M] Doing OCR for region {X=827,Y=1241,Width=827,Height=1098} on bitmap WxH: 1654x2339
20191003.224203 [OCR] INFO  [ThreadOCR] [3.533M] Got 4 words
20191003.224203 [OCR] INFO  [ThreadOCR] [3.533M] -Doing OCR
20191003.224203 [OCR] INFO  [ThreadOCR] [3.533M] Found 497 words (D:\Qiqqa\base\C9F0D079-EE4C-4A15-8547-72164A7A356D\documents\9\9EEFF1545A5CDA5850D698A202563CDC6322CE0.pdf @ #6)
20191003.224203 [OCR] INFO  [Main] [3.533M] We have an OCR word list of length 497
20191003.224203 [OCR] INFO  [Main] [3.541M] +Writing OCR to file C:\Users\Ger\AppData\Local\Temp\TempFile.aec52fbb-2cde-43fd-9c47-8bd72eddc0bb.txt
```

**Comment by GerHobbelt** [comment]
And the example PDF:

[9EEFF1545A5CDA5850D698A202563CDC6322CE0.pdf](https://github.com/GerHobbelt/qiqqa-open-source/files/3688354/9EEFF1545A5CDA5850D698A202563CDC6322CE0.pdf)

**Comment by GerHobbelt** [comment]
Closing as a duplicate of https://github.com/jimmejardine/qiqqa-open-source/issues/73
